apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260518-135315-f9ijsiav5efd-service
spec:
  selector:
    app: enterprise-system-20260518-135315-f9ijsiav5efd
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
